services:
  backend:
    build:
      context: ./cms-catalog-backend
      dockerfile: Dockerfile
    container_name: cms_backend
    # Semua konfigurasi DB_HOST, DB_USER, dll diambil dari sini
    env_file:
      - ./cms-catalog-backend/.env
    ports:
      - "3000:3000"
    volumes:
      - uploaded_files:/app/uploads
    depends_on:
      database:
        condition: service_healthy

  frontend:
    image: userbatik/company-profile-batik:latest
    restart: always
    container_name: company-profile-frontend
    env_file:
      - ./company-profile-batik/.env
    ports:
      - "3001:3001"
    pull_policy: always
    depends_on:
      - backend

  cms:
    build:
      context: ./dashboard-cms
      dockerfile: Dockerfile
    container_name: cms_app
    env_file:
      - ./dashboard-cms/.env
    environment:
      - ESLINT_NO_DEV_ERRORS=true 
      - DISABLE_ESLINT_PLUGIN=true 
    ports:
      - "3002:3002"
    depends_on:
      - backend

  database:
    image: mysql:8.0
    container_name: mysql_db
    # Port 3306 dibuka agar bisa diakses dari aplikasi luar/DB tool seperti TablePlus
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=cms_catalog_db
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ptest"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    container_name: nginx_gateway
    restart: always
    ports:
      - "80:80"    # Membuka Port 80 (HTTP Standar) ke Publik
      - "81:81"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf # Load config kamu tadi
    depends_on:
      - backend
      - frontend
    networks:
      - default

volumes:
  mysql_data:
  uploaded_files: