services:
  backend:
    build:
      context: ./cms-catalog-backend
      dockerfile: Dockerfile
    container_name: cms_backend
    # Semua konfigurasi DB_HOST, DB_USER, dll diambil dari sini
    env_file:
      - ./cms-catalog-backend/.env.prod
    ports:
      - "3000:3000"
    volumes:
      - uploaded_files:/app/uploads
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build:
      context: ./company-profile-batik
      dockerfile: Dockerfile
    container_name: company-profile-frontend
    env_file:
      - ./company-profile-batik/.env.prod
    ports:
      - "3001:3001"
    depends_on:
      - backend

  cms:
    build:
      context: ./dashboard-cms
      dockerfile: Dockerfile
    container_name: cms_app
    env_file:
      - ./dashboard-cms/.env.prod
    ports:
      - "3002:3002"
    depends_on:
      - backend

  database:
    image: mysql:8.0
    container_name: mysql_db
    # Port 3306 dibuka agar bisa diakses dari aplikasi luar/DB tool seperti TablePlus
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=cms_catalog_db
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p", "test"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
  uploaded_files: