services:
  backend:
    volumes:
      - uploaded_files:/app/uploads
    build:
      context: ./cms-catalog-backend
      dockerfile: Dockerfile
    container_name: cms_backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=test
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build:
      context: ./company-profile-batik
      dockerfile: Dockerfile
    container_name: company-profile-frontend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - BACKEND_API_URL=192.168.1.53:3000/api
    depends_on:
      - backend

  cms:
    build:
      context: ./dashboard-cms
      dockerfile: Dockerfile
    container_name: cms_app
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - BACKEND_API_URL=192.168.1.53:3000/api
    depends_on:
      - backend

  database:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=cms_catalog_db
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
  uploaded_files:
